### ISSUE TITLE
Disconnects are not handled

### ISSUE THREAD

**Issue by nicholasrobinson** [nicholasrobinson/node-smartcielo#1]
Disconnects result in an unresponsive interface, with no indication of issue. The code should attempt to reconnect automatically (with exponential back-off), or fail with reason.

**Comment by dberlin** [comment]
So, this is clearly a signalR based server - is there a reason you don't just use the signalR javascript client package?
https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0

Besides removing most of the code you have, it also supports auto-reconnect.

**Comment by nicholasrobinson** [comment]
@dberlin I had no idea that the signalr client was open source! I’ll keep this in mind in my next update! Eliminating the communication code would make this a lot easier!! Feel free to raise a PR!

**Comment by nicholasrobinson** [comment]
@dberlin Quick update:

I threw together a quick test using the [ASP.NET Core SignalR JavaScript Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0) you referenced (aka [@microsoft/signalr](https://www.npmjs.com/package/@microsoft/signalr)). 

I encountered the following error:

```
[2021-02-23T07:19:39.037Z] Error: Failed to start the connection: Error: Detected a connection attempt to an ASP.NET SignalR Server. This client only supports connecting to an ASP.NET Core SignalR Server. See https://aka.ms/signalr-core-differences for details.
```

Reading the referenced documentation suggests we should instead be using the [ASP.NET SignalR Client](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client) (aka [signalr](https://www.npmjs.com/package/signalr))

I'll give that a shot and see what happens!

**Comment by nicholasrobinson** [comment]
@dberlin Last update for the night:

Going down the rabbit hole, I quickly discovered that the [ASP.NET SignalR Client](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client) (aka [signalr](https://www.npmjs.com/package/signalr)) is NOT very nodejs friendly. It is heavily browser/jquery dependent. Probing further, I end up on [StackOverflow](https://stackoverflow.com/questions/59073136/trying-to-run-signalr-client-on-the-server-side-nodejs) and then at [another GitHub project](https://github.com/alex8088/node-signalr), which is eerily similar to the signalr client code that I have already written. 

Unless you have further insights, I am thinking that simply adding reconnect logic to the existing codebase is the path of least resistant here.

**Comment by dberlin** [comment]
Sigh. Yeah, I've only ever used the old one from the browser, but knew it
had an npm package, so figured it would work out.
Good to hear the new client works, but sad to hear the old one is so bad at
this.

I think what you are saying sounds right - unless it gets
significantly more complex, probably not worth doing anything else.

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/node-smartcielo/issues/19
