### ISSUE TITLE
Nothing happens with MrCool AC

### ISSUE THREAD

**Issue by nayefag** [nicholasrobinson/node-smartcielo#10]
Hi,

I have configured MrCool AC (3rd gen 24K BTU) on home bridge as described in the documentation. I can see commands being sent in the homebridge logs, but no action happens on the AC and the status is not updated (temperature shows as 75 and AC is still off).

[5/4/2021, 6:47:05 AM] Homebridge v1.3.4 (Homebridge 3BEE) is running on port 51368.
[5/4/2021, 6:47:39 AM] [MrCool AC] Sending power on
[5/4/2021, 6:47:49 AM] [MrCool AC] Setting mode to cool
[5/4/2021, 6:48:12 AM] [MrCool AC] Sending power on
[5/4/2021, 6:48:22 AM] [MrCool AC] Setting mode to cool
[5/4/2021, 6:55:35 AM] [MrCool AC] Room temperature updated to 75 °F / 24 °C

Could this be something wrong in my config or did the smartcielo website changed things ?

I have double / triple checked my config and it looks ok. Do I need to open up network ports for access ? (the MrCool app works fine without me opening up any ports).

Thanks.

**Comment by dVIAN13** [comment]
I am having a similar issue. Plugin updates the status in home just fine, however I cannot send commands to the unit. It reverts back to what the app was last set to. 

if I change in the mrcool app, home status updates. 
if I change in home, it reverts back after a few seconds/minutes.

@nicholasrobinson - any input on the potential problem? thanks!

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/node-smartcielo/issues/19
