### ISSUE TITLE
Invalid json body on https://home.cielowigle.com/cAcc

### ISSUE THREAD

**Issue by GregBeebe** [nicholasrobinson/node-smartcielo#13]
Configured plugin on Homebridge restart the following error occurs. Also, as a point of clarity, do I really need to enter my public facing IP (WAN) or the local Mr. Cool IP address (LAN). 

`[11/4/2021, 6:11:08 PM] [Mr. Cool] FetchError: invalid json response body at https://home.cielowigle.com/cAcc reason: Unexpected token < in JSON at position 0
    at /homebridge/node_modules/homebridge-smartcielo/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getAccessCredentials (/homebridge/node_modules/homebridge-smartcielo/node_modules/node-smartcielo/SmartCielo.js:147:31)
    at async Promise.all (index 1) {
  type: 'invalid-json'
}`

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/node-smartcielo/issues/19
