### ISSUE TITLE
Project no longer supported?

### ISSUE THREAD

**Issue by dVIAN13** [nicholasrobinson/node-smartcielo#14]
Is this project no longer supported? @nicholasrobinson

**Comment by nicholasrobinson** [comment]
I’m still here @dVIAN13 ! If you have a specific issue please raise a ticket or propose a PR.

**Comment by dVIAN13** [comment]
Glad to see you're still around! Is there anything we can add in the pending issues to help diagnose them and get them addressed/fixed? in both node-smartcielo and homebridge-smartcielo. thanks!
