### ISSUE TITLE
sendFanSpeed() does not work

### ISSUE THREAD

**Issue by nicholasrobinson** [nicholasrobinson/node-smartcielo#2]
The API does not appear to do anything.

**Comment by androolloyd** [comment]
Curious how the app is sending it? Possible to get it through an mqtt request?

**Comment by nicholasrobinson** [comment]
@androolloyd 
> Curious how the app is sending it?

The app sends ALL commands as WebSocket messages to Cielo's API.

The [node-smartcielo](https://github.com/nicholasrobinson/node-smartcielo) API wraps a similar WebSocket message. The implication is that I may have made a mistake in constructing the sendFanSpeed() payload.

**Comment by nicholasrobinson** [comment]
@androolloyd
> Possible to get it through an mqtt request?

That is not within the scope of the node-smartcielo wrapper interface. I have not seen any evidence of MQTT support within Cielo's API.

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/node-smartcielo/issues/19
