### ISSUE TITLE
Multiple devices support

### ISSUE THREAD

**Issue by m-alzahrani** [nicholasrobinson/node-smartcielo#4]
Good day sir, 
first of all ,Thanks for your hard work 

I have two issues the first one is the code doesn't support multiple devices as you stated and I have 3 devices under one user . and I have some JSON data that I got from monitoring the website API using developer tool. I hope it could help

```
{"code":0,"message":"SUCCESS","data":
	{
		"isDbUpdate":false,
		"listDevices":[
			{
			"turbo":null,
			"turboConfig":null,
			"isTurboDisplay":null,
			"isFreezePointDisplay":null,
			"freezePointConfig":null,
			"isOnceSyncedState":0,
			"isScreenLess":0,
			"deviceName":"Dinner Room",
			"blockMessage":"Unblocked",
			"latEnv":{"temp":"29.0","humidity":"44.0"},
			"macAddress":"XXXXXXXXX",
			"userId":"XXXXXXX",
			"isEnergyDevice":0,
			"applianceType":"AC",
			"wifiName":"Muha_2.4",
			"deviceId":"BiHzlG",
			"latestAction":{},
			"lastAction":null,
			"applianceID":1640,
			"createdAt":"1590774430",
			"deviceFilterDuration":"70",
			"deviceStatus":"1",
			"deviceImageUrl":null,
			"isBlocked":0,
			"deviceFilterFlag":1,
			"broadcastName":"Cielo_BP01_339F00",
			"fwVersion":"1.0.4,2.3.6",
			"deviceType":"BREEZ-PLUS",
			"deviceTypeVersion":"BP01",
			"applianceSubtype":1,
			"deviceSettings":{},
			"groupId":"-1",
			"deviceTimeZone":"+3:0",
			"latestBucketError":"0",
			"myRules":[],
			"fpFailureAttempts":"0",
			"turboFailureAttempts":"0",
			"isFaren":0
		},
		{
			"turbo":null,
			"turboConfig":null,
			"isTurboDisplay":null,
			"isFreezePointDisplay":null,
			"freezePointConfig":null,
			"isOnceSyncedState":0,
			"isScreenLess":0,
			"deviceName":"Living Room"....etc
		},
"error":null,"status":200}
```
 it list all devices in JSON code I didn't but the whole JSON it's a lot of data

the second issue when I setup my Homebridge plugin I can see a device but with false information and it doesn't send any data to my devices . You said it maybe the payload when I check the websocket payload I find it to close to yours except some data missing and here is the payload for my device.

```
{"H":"devicesactionhub","M":"broadcastActionAC",
	"A":[{
	"tempRange":"",
	"turbo":"off",
	"mid":"felajxtaoawwqhdlebdsar0d",
	"mode":"cool",
	"modeValue":"",
	"temp":"27",
	"tempValue":"",
	"power":"on",
	"swing":"auto",
	"fanspeed":"auto",
	"scheduleID":"",
	"macAddress":"XXXXXXXX",
	"applianceID":1880,
	"performedAction":"power",
	"performedActionValue":"on",
	"actualPower":"off",
	"modeRule":"",
	"tempRule":"default",
	"swingRule":"default",
	"fanRule":"default",
	"isSchedule":false,
	"aSrc":"WEB",
	"ts":1591907244,
	"deviceTypeVersion":"BP01",
	"deviceType":"BREEZ-PLUS",
	"light":"",
	"rStatus":"",
	"fwVersion":"1.0.4,2.3.6",
	"exe":""
	}]
,"I":0}
```

I am sorry if there is anything wrong , I just started using Home Assistant, Python and JSON
Never used it before

**Comment by nicholasrobinson** [comment]
Just bought a second MRCOOL A/C, so this issue *shoud* get some attention in the next few weeks. 🤞

**Comment by forevaclevah** [comment]
Nice! :-) Though, it wouldn't be too difficult to just make individual user accounts for each AC.

**Comment by Cjkeenan** [comment]
Sorry if this is obvious, but what do you guys mean by one device only? Is that one contained system up to 4-zones or is that only a single indoor unit?

**Comment by forevaclevah** [comment]
One account, multiple indoor units. In my example, I have two 1:1 systems and one 3:1 system. It shows up as five different units when I log in to Cielo.

In my experience, smartcielo didn’t consistently send commands to one unit. It seemed to jump around. I have since moved to sensibo for controls and HomeKit integration, however I am willing to test updated smartcielo code as it comes out.

**Comment by timstring** [comment]
Over a year since this issue was first raised, and I am having the same problem!  Any fix in sight?

**Comment by aotearoacoder** [comment]
Has anyone done any work on this issue?

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/node-smartcielo/issues/19
