### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by dhpeter** [nicholasrobinson/node-smartcielo#6]
I set installed and input the details in the config.json but when i throw up homebridge i get:

Type Error: Cannot read property 'getAttribute' of null

I also am not sure how to identify the public ip i can only get the private IP so maybe they are related? Additionally, I set up the device using login with Apple...also could be related.

**Comment by androolloyd** [comment]
Google what is my ip and you’ll get your public IP

**Comment by dhpeter** [comment]
Thank’s I figured – is the error I got symptomatic of the IP issue? Or does it not support login with apple

**Comment by androolloyd** [comment]
Oh you can't login with Apple, this is incredibly frustrating lol, its because the apple id generates a random pw, and provides that for login, but the password isn't available for you to get, its one of their one time creation, and the app doesn't let you change it with an apple id.

Just create a new account with an email alias, and go that route. Worked for me.

**Comment by nicholasrobinson** [comment]
Apologies for the delayed response:

@dhpeter 
> I also am not sure how to identify the public ip

What @androolloyd suggested is correct. For simplicity, you can visit http://nicholasrobinson.me/ip.php and you will be shown your public IP.

Note: I am not sure if this field *needs* to be accurate, i.e. I am not sure if it matters what you configure for IP address.

@dhpeter 

> I set up the device using login with Apple...also could be related.

> I set installed and input the details in the config.json but when i throw up homebridge i get:

`Type Error: Cannot read property 'getAttribute' of null`

I believe that what @androolloyd says is correct:

> Oh you can't login with Apple

I do not know this for fact thought, so your mileage may vary. I personally use email and password, so this is what is tested/supported.

**Comment by nicholasrobinson** [comment]
I am assuming this issue is explained by the inability to login with Apple Credentials, so I am closing this issue. If this is the case, please file a separate issue requesting support for Apple login.
