### ISSUE TITLE
Beeping on schedule power on

### ISSUE THREAD

**Issue by philazzi44** [nicholasrobinson/node-smartcielo#9]
Looking over the code written so far (which is awesome, btw!), I'd love to see support for some way to power on the unit **without** the beeping that accompanies it... I can reproduce this on the 3rd gen Mr Cool Multi zone unit I just installed. It effectively turns a morning power on schedule to heat/cool the room into an unintended alarm clock for anyone sleeping in the room.

I'm aware that hitting the LED button on the remote **after** the unit is on will mute the beeping up until the unit powers down. I imagine it might be possible to keep the unit on all night, and lower the target temperature such that it acts as a fan all night, but that seems inefficient compared to powering down for at least 8 hours. I suspect what I'm reporting may not be possible with the firmware on the unit, which would be unfortunate, but perhaps something to track as firmware updates are released.

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/node-smartcielo/issues/19
